### PR TITLE
Application memory leak found and fixed (#264)

### LINKED ISSUE #264: Memory leak in App
Screenshot 2020-12-24 at 13 49 32

OpenJ9 cmd opts:
https://www.eclipse.org/openj9/docs/cmdline_migration/

### PR DESCRIPTION
**Pull request by kyberorg**
Fix #264 by implementing #269

### CODE REVIEW

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -41,6 +41,15 @@ export JAVA_OPTS="$JAVA_OPTS -XX:+UseContainerSupport"
 export JAVA_OPTS="$JAVA_OPTS -XX:+AlwaysActAsServerClassMachine"
 export JAVA_OPTS="$JAVA_OPTS -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/dumps"
 
+## Issue 264 (OpenJ9 tuning). Based on https://yals.eu/dUxHlC
+export JAVA_OPTS="$JAVA_OPTS -Xgcpolicy:gencon"
+export JAVA_OPTS="$JAVA_OPTS -Xquickstart"
+export JAVA_OPTS="$JAVA_OPTS -Xtune:virtualized"
+export JAVA_OPTS="$JAVA_OPTS -XX:+ClassRelationshipVerifier"
+export JAVA_OPTS="$JAVA_OPTS -XX:-TransparentHugePage"
```
Comment (kyberorg) [inline docker-entrypoint.sh]: Should be enabled

File: docker-entrypoint.sh [hunk 2]
```diff
@@ -41,6 +41,15 @@ export JAVA_OPTS="$JAVA_OPTS -XX:+UseContainerSupport"
...
+export JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=90"
```
Comment (kyberorg) [inline docker-entrypoint.sh]: This allows to use up to 90% of host memory.

File: src/main/resources/application.properties [hunk 3]
```diff
@@ -13,6 +13,10 @@ spring.jpa.hibernate.ddl-auto=create-drop
 spring.datasource.url=jdbc:h2:mem:yals;DB_CLOSE_ON_EXIT=FALSE
 spring.datasource.username=${DB_USER:sa}
 spring.datasource.password=${YALS_DB_PASSWORD:sa}
+#Auto reconnect
+spring.datasource.hikari.max-lifetime=600000
```
Comment (kyberorg) [inline src/main/resources/application.properties:17]: Add comment about 10 mins
