### PR TITLE
Fixing UI Tests

### LINKED ISSUE #224: UI Tests
- [x] Migrate Grid (or use Zalenium) to CI Server. Remove QA

- [x] Migrate from Vaadin TestBench to Selenide with our custom methods for Vaadin 

- [x] Write Vaadin methods as separate as possible. Later on there is plan to extract 'em as separate lib

### PR DESCRIPTION
**Pull request by kyberorg**
Fix #224

### CODE REVIEW

File: src/test/java/eu/yals/test/TestUtils.java [hunk 1]
```diff
@@ -117,16 +104,27 @@ public static void assertEmpty(String message, String string) {
...
-        } else {
-            localUrl = String.format("http://localhost:%d", serverPort);
+        if(StringUtils.isNotBlank(System.getProperty(TestApp.Properties.TEST_URL, ""))) {
+            return System.getProperty(TestApp.Properties.TEST_URL);
+        }
+
+        TestApp.RunMode runMode = TestApp.RunMode.valueOf(
+                System.getProperty(TestApp.Properties.TEST_RUN_MODE, TestApp.RunMode.LOCAL.name()));
+
+        switch (runMode) {
```
Comment (kyberorg) [inline src/test/java/eu/yals/test/TestUtils.java:115]: Codacy found an issue: [A switch statement does not contain a break](https://app.codacy.com/gh/yadevee/yals/pullRequest?prid=6385434)

**Comment by kyberorg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/test/java/eu/yals/test/ui/usage/CorrectInputTest.java  1
- src/test/java/eu/yals/test/utils/vaadin/VaadinUtils.java  1
- src/test/java/eu/yals/test/utils/YalsTestDescription.java  1
- src/test/java/eu/yals/test/ui/SelenideTest.java  4
- src/test/java/eu/yals/test/pageobjects/HomePageObject.java  2
- src/test/java/eu/yals/test/ui/usage/MultiStepTest.java  1
- src/test/java/eu/yals/test/ui/home/HomePageTest.java  1
- src/test/java/eu/yals/test/ui/home/VisibleStateTest.java  2
- src/test/java/eu/yals/test/ui/usage/IdnTest.java  1
- src/test/java/eu/yals/test/ui/usage/AbnormalUsageTest.java  1
- src/test/java/eu/yals/test/utils/SelenideUtils.java  2
- src/test/java/eu/yals/test/utils/vaadin/elements/TextFieldElement.java  1
- src/test/java/eu/yals/test/ui/usage/IncorrectInputTest.java  1
- src/test/java/eu/yals/test/ui/appinfo/PublicInfoTest.java  1
         

Complexity decreasing per file
==============================
+ src/test/java/eu/yals/test/TestUtils.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/yadevee/yals/pullRequest?prid=6385434&bid=20709225)

**Comment by kyberorg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/test/java/eu/yals/test/ui/usage/IdnTest.java  1
- src/test/java/eu/yals/test/ui/appinfo/PublicInfoTest.java  1
- src/test/java/eu/yals/test/utils/vaadin/elements/TextFieldElement.java  1
- src/test/java/eu/yals/test/ui/SelenideTest.java  4
- src/test/java/eu/yals/test/utils/SelenideUtils.java  2
- src/test/java/eu/yals/test/ui/usage/IncorrectInputTest.java  1
- src/test/java/eu/yals/test/utils/vaadin/VaadinUtils.java  1
- src/test/java/eu/yals/test/ui/usage/AbnormalUsageTest.java  1
- src/test/java/eu/yals/test/ui/usage/MultiStepTest.java  1
- src/test/java/eu/yals/test/ui/home/HomePageTest.java  1
- src/test/java/eu/yals/test/ui/home/VisibleStateTest.java  2
- src/test/java/eu/yals/test/utils/YalsTestDescription.java  1
- src/test/java/eu/yals/test/ui/usage/CorrectInputTest.java  1
- src/test/java/eu/yals/test/pageobjects/HomePageObject.java  2
         

Complexity decreasing per file
==============================
+ src/test/java/eu/yals/test/TestUtils.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/yadevee/yals/pullRequest?prid=6385434&bid=20709225)

**Comment by kyberorg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/test/java/eu/yals/test/ui/usage/CorrectInputTest.java  1
- src/test/java/eu/yals/test/utils/vaadin/VaadinUtils.java  1
- src/test/java/eu/yals/test/ui/SelenideTest.java  4
- src/test/java/eu/yals/test/ui/usage/MultiStepTest.java  1
- src/test/java/eu/yals/test/utils/SelenideUtils.java  2
- src/test/java/eu/yals/test/ui/home/HomePageTest.java  1
- src/test/java/eu/yals/test/pageobjects/HomePageObject.java  2
- src/test/java/eu/yals/test/ui/usage/IdnTest.java  1
- src/test/java/eu/yals/test/ui/usage/IncorrectInputTest.java  1
- src/test/java/eu/yals/test/ui/home/VisibleStateTest.java  2
- src/test/java/eu/yals/test/utils/vaadin/elements/TextFieldElement.java  1
- src/test/java/eu/yals/test/ui/usage/AbnormalUsageTest.java  1
- src/test/java/eu/yals/test/utils/YalsTestDescription.java  1
- src/test/java/eu/yals/test/ui/appinfo/PublicInfoTest.java  1
         

Complexity decreasing per file
==============================
+ src/test/java/eu/yals/test/TestUtils.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/yadevee/yals/pullRequest?prid=6385434&bid=20709225)
